subscription getNewInvites($user_id: String, $country: String, $locality: String, $place:String, $poi: String, $postcode: String) {
  Invites(
    limit: 1,
    order_by: {uid:desc},
    where: {_or: 
    [
      {sender: {_eq: $user_id}}, 
      {
    		Address: {
    			_and: [
      			{country: {_eq:$country}},
      			{locality:{_eq:$locality}},
      			{place:{_eq:$place}},
      			{poi:{_eq:$poi}},
      			{postcode:{_eq:$postcode}}
    			]
        }
  	  }
    ]})
  {
    description
    price
    takeaway
    alternativeAddress
    date
    event
    female
    male
    sender_id: sender
    uid
    photoUrl
    User {
      user_id
      name,
      familly,
      photoUrl,
    }
    Address {
      country
      locality
      place
      poi
      postcode
    }
  }
}
